{% set version = "0.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinydisconnect
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinydisconnect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinydisconnect/shinydisconnect_{{ version }}.tar.gz
  sha256: 4c7ec442b965b4645b2e9fc0eab2c45b0009316735dace23227f5f89babb17fa

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-glue
    - r-htmltools
    - r-shiny >=1.0
  run:
    - r-base
    - r-checkmate
    - r-glue
    - r-htmltools
    - r-shiny >=1.0

test:
  commands:
    - $R -e "library('shinydisconnect')"           # [not win]
    - "\"%R%\" -e \"library('shinydisconnect')\""  # [win]

about:
  home: https://github.com/daattali/shinydisconnect
  license: MIT
  summary: 'A ''Shiny'' app can disconnect for a variety of reasons: an unrecoverable error occurred in the app, the server went down, the user lost internet connection, or any other reason that might cause the ''Shiny'' app to lose connection to its server. With ''shinydisconnect'', you can call disonnectMessage() anywhere
    in a Shiny app''s UI to add a nice message when this happens. Works locally (running Shiny apps within ''RStudio'') and on Shiny servers (such as shinyapps.io, ''RStudio Connect'', ''Shiny Server Open Source'', ''Shiny Server Pro''). See demo online at <https://daattali.com/shiny/shinydisconnect-demo/>.'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
